name: Bug report
description: Are you getting false positives? Is a supported rule not working for you? Open a bug report.
title: 'Bug report'
body:
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current behaviour
      description: Here you can summarise what is going on.
      placeholder: e.g. ESLint marked an unused variable starting with `_` as unused, even though I added this pattern to my `eslint.config.js`.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Describe what you would expect to happen instead.
      placeholder: e.g. I expected my linter to pass.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Providing a set of concise steps that deterministically reproduce the behaviour helps us investigate what is going on.
      placeholder: |
        For example:
        1. I imported `@code-pushup/eslint/javascript` in my `eslint.config.js`.
        2. I added explicit options to the `no-unused-vars` rule.
        3. When I opened the `index.ts` file, ESLint highlighted the `no-unused-vars` rule despite the variable `_unused` matching the pattern I explicitly set.
    validations:
      required: true
  - type: input
    id: working-version
    attributes:
      label: Has this worked for you before?
      description: Provide the last working version.
      placeholder: e.g. 0.12.0
  - type: dropdown
    id: config
    attributes:
      label: Which configuration is this related to?
      options:
        - javascript
        - typescript
        - node
        - angular
        - ngrx
        - react
        - graphql
        - jest
        - vitest
        - cypress
        - playwright
        - storybook
        - react-testing-library
    validations:
      required: true
  - type: textarea
    id: plugin-versions
    attributes:
      label: Config and peer dependencies versions
      description: What config version are you running? Include peer dependencies if applicable.
      placeholder: |
        For example:
        `@code-pushup/eslint-config` version 0.12.0

        Peer dependencies:
        - `typescript-eslint` version 8.13.0
        - `eslint-plugin-sonarjs` version 1.0.4
    validations:
      required: true
  - type: input
    id: eslint-version
    attributes:
      label: ESLint version
      description: What ESLint version are you running? (check with `npm list eslint`)
      placeholder: e.g. 9.14.0
    validations:
      required: false
  - type: input
    id: ts-version
    attributes:
      label: TypeScript version
      description: What TypeScript version are you running? (check with `npx tsc -v`)
      placeholder: e.g. 5.6.3
    validations:
      required: false
  - type: input
    id: node-version
    attributes:
      label: Node version
      description: What Node version are you running? (check with `node -v`)
      placeholder: e.g. 22.12.0
    validations:
      required: false
