name: New configuration request
description: Are you missing support for a framework or a library? Open a configuration request.
title: 'New configuration request'
body:
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: Here you can phrase your request in a user story format which highlights the added value of the requested configuration.
      placeholder: e.g. As a developer, I want to support <configuration>, so that <added value>.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: What should the new configuration contain? Listing a set of criteria helps us determine whether the scope of the request was fully addressed.
      placeholder: |
        For example:
        - [ ] A new configuration `@code-pushup/eslint-config/react` extends `plugin:react/recommended` with additional rules …
    validations:
      required: true
