#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# tests
npx nx run eslint-config:test

# docs script
npx nx run eslint-config:docs
git add packages/eslint-config/docs packages/eslint-config/README.md

# Prettier (https://prettier.io/docs/en/precommit.html#option-5-shell-script)
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
echo "$FILES" | xargs git add
